spring.datasource.url=jdbc:postgresql://dpg-d7sm13r7uimc7386fmeg-a.virginia-postgres.render.com:5432/inventory_db_jtvg
spring.datasource.username=inventory_db_jtvg_user
spring.datasource.password=0RfcentREBXraLWX7TzI5suddaIOi3yN

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
server.port=${PORT:8080}
server.address=0.0.0.0

spring.main.allow-bean-definition-overriding=true